image: golang:1.12

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/gopkg.in

stages:
  - bench
  - build

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - make build
bench:
  stage: bench
  artifacts:
    paths:
      - bench.txt
      - benchcmp
  script:
    - make bench
