stages:
  - test
  - build

cache:
  paths:
    - /apt-cache
    - /go/src/

test:
  stage: test
  image: circleci/golang:1.12-stretch
  artifacts:
    paths:
      - /tmp/test.txt
  script:
    - make test

benchmark:
  stage: test
  image: circleci/golang:1.12-stretch
  artifacts:
    paths:
      - /tmp/benchmark.txt
      - /tmp/benchmark_change.txt
  script:
    - make benchmark

build:
  stage: build
  image: circleci/golang:1.12-stretch
  artifacts:
    paths:
      - dist/
  script:
    - make build
