image: golang:1.12

stages:
  - test
  - build

cache:
  paths:
    - /apt-cache
    - /go/src/

before_script:
  - go mod download

test:
  stage: test
  artifacts:
    paths:
      - test.txt
  script:
    - make test branch='${CI_COMMIT_REF_SLUG}'

test_blog:
  stage: test
  script:
  - cd examples/blog; go run ../../*.go build

test_iterators:
  stage: test
  script:
    - cd examples/iterators; go run ../../*.go build

test_simplePage:
  stage: test
  script:
    - cd examples/simplePage; go run ../../*.go build

benchmark:
  stage: test
  artifacts:
    paths:
      - benchmark.txt
      - benchmark_change.txt
  script:
    - make benchmark

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - make build
